features:
  categorical:
    - team1
    - team2
    - toss_winner
    - toss_decision
    - venue
    - match_type
    - super_over
    - batting_first
    - chasing_team


  numerical:
    - season
    - req_rr

dataPath:
  file: ipl.csv
  path: data/
